### PR TITLE
Proper fragment usage, unified usage of PlayableQRCode and QRLocation

### PR DESCRIPTION
**Pull request by Mattwmaster58**
This supercedes #239, I guess I should've structured this better to not depend like that, or roll them all up into one.

This pull request tries to do 2 things:
 - a major refactor to clean things up around the scanning or QR codes. Previously, data was haphazardly passed without bundling and without organization, and this PR attempts to fix some/most of that clutter and disorganization.
 - image uploading

#### Changes to `PlayableQRCode`

 - Since this class _always_ will be associated with a player, I went ahead and added this as part of the class. In this case, we needed the player anyway, so this reduced what we have to pass to the FragmentAddQRCode when adding a QR Code.
 - This class was made serializable, which means we can put it into a bundle so if the fragment gets killed (for example, this actually happened to me while uploading the image. Since we start a new activity, android is free to kill off that fragment, and when we get back from the camera app, we're SOL if we don't save anything to the bundle.
   - QRLocation was also made serializable to accommodate this as well
 - This class was also made "firestore serializable" which means we can directly insert the object into the database, and the necessary serialization will take place. We can also get it back like so (may be of use to @niazieo, @Holy-Hero for their stuff, dk what the rest of you are working on):
 ```java
QueryDocumentSnapshot doc = ...
PlayableQRCode code = doc.toObject(PlayableQRCode.class)
```
  **The only caveat** that I know of right now is that playerId does not get set automatically - I'm still trying to figure out if this can even be done at all. Manually, calling `PlayableQRCode.setPlayerId(doc.getReference().getParent().getParent().getId())` should work ™️ 
 - Changed the method names AddQRToDatabase → addToDb to be more consistent w/ naming
 - QRLocation handles lat/long universally now, and removes the need for the programmer to ever think of geohashes again, except eg when they need to query for them specifically

## Other changes
 - Anywhere a lambda function could be used, I did, because I don't see a point in the verbosity of classes (see [here](https://github.com/CMPUT301W22T00/QRHunt/compare/qrcode-serialization?expand=1#diff-4d661e6beeac056ce6f2603a9b3bdd3d350a546f313d7222f3212361abe94185L70) for a dramatic example - from 16 lines to 5
 - I seem to recall code @kezzayuno wrote with a snapshot listener because I was going to improve it, but I can't seem to find any mention of it anymore 😬. At this point I'm too lazy to go find a reference to it, maybe tomorrow
 - renamed `AugmentedCamera` → `QRCodeProcessor`. The first name makes 0 sense IMO

## Image Uploading

Images are uploaded to Firebase Storage, the bucket currently allows every path unlimited r/w access. Maybe one day I'll fix this, lol. There's not much to say about this, the database receives an image URL. In the future, I need to implement deleting images when the QR code is deleted, this would be a job for cloud functions. You can't delete a image based on URL, but you need a reference, which is a separate type of path. Lucky for us, I just store the images in the most logical way possible (/qrCodes/userId/qrCodeId) so we can come up with the reference based on the user's ID and QR ID. Images are compressed to JPEGs with quality set to 85, which I think is a semi decent balance of quality/size.

### Unfinished
 - The layout contains a progress bar (think loading spinner icon thingy, this is just what android calls them for some reason) which currently shows up in a random spot. I'd like to have some sort of overlay instead, but I haven't gotten around to this.
 - FragmentLibraryRemoveQR.java and QRLibrary are kinda in a half baked err half mise en place - I unfortunately branched from a branch which had these...sorry. I don't know if/how hard this is to undo so this is the small price we pay for a refactor - some random code into main 
 - FragmentProfile.java

### CODE REVIEW

**Comment by Mattwmaster58** [comment]
also I made this a draft because I really want critical comments (and not merged as soon as it builds 😉), i know a lot of this is long changes but if you have any questions about my approach please lmk, I wrote this at like 5am so we would both stand to benefit from another pair of eyes on this

**Comment by kezzayuno** [comment]
For the "FragmentLibraryRemoveQR.java and QRLibrary are kinda in a half baked err half mise en place - I unfortunately branched from a branch which had these...sorry. I don't know if/how hard this is to undo so this is the small price we pay for a refactor - some random code into main". Does this break the application at the moment?

**Comment by Holy-Hero** [comment]
It should be too hard to fix QRLibrary and FragmentLibraryRemoveQR. From what I understand, lamda function is replacing the new "classname" for .set"classname", correct me if I'm wrong. Everything looks good, Great work

**Review by kezzayuno — APPROVED** [review]

**Comment by Mattwmaster58** [comment]
@kezzayuno 
> when do you recall me talking about it (in what context)?

I just saw the code and if I remember correctly the blame (git blame, I'm not blaming problems lol) was on you. Didn't want to reduce functionality somehow with a bad merge.

> Does this break the application at the moment?

No

**Pull request merged**
